name: bootcamp deployment
on:
  push:
    branches:
      - main
jobs:
  build_mockserver:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/mock_server/
    steps:
      - name: clone repo
        uses: actions/checkout@v2
      - name: docker login to github container registry
        uses: docker/login-action/@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: build docker images
        run: docker build . -t ${{ secrets.REGISTRY}}/${{ secrets.REGISTRY_USERNAME}}/bc58-data
      - name: images
        run: | 
            docker images
      

  